// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR61izdAa7ubcN5xB3WYGOz639BJdcrg4',
    appId: '1:636479501272:web:80feba0f7913269d7778ad',
    messagingSenderId: '636479501272',
    projectId: 'app-receita-da11c',
    authDomain: 'app-receita-da11c.firebaseapp.com',
    databaseURL: 'https://app-receita-da11c-default-rtdb.firebaseio.com',
    storageBucket: 'app-receita-da11c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmUFeUaPKeKQ0EpXSdQvnRw20Gvpg2N-Q',
    appId: '1:636479501272:android:3b0a3c84477b54887778ad',
    messagingSenderId: '636479501272',
    projectId: 'app-receita-da11c',
    databaseURL: 'https://app-receita-da11c-default-rtdb.firebaseio.com',
    storageBucket: 'app-receita-da11c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPxjG8GNGZA1k2nepdKA0z3gqo1XExg3s',
    appId: '1:636479501272:ios:87abc9b13f50212d7778ad',
    messagingSenderId: '636479501272',
    projectId: 'app-receita-da11c',
    databaseURL: 'https://app-receita-da11c-default-rtdb.firebaseio.com',
    storageBucket: 'app-receita-da11c.appspot.com',
    iosClientId: '636479501272-r0nla6cj545n82qn991tluo8kq3n2u9j.apps.googleusercontent.com',
    iosBundleId: 'com.receitas.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPxjG8GNGZA1k2nepdKA0z3gqo1XExg3s',
    appId: '1:636479501272:ios:87abc9b13f50212d7778ad',
    messagingSenderId: '636479501272',
    projectId: 'app-receita-da11c',
    databaseURL: 'https://app-receita-da11c-default-rtdb.firebaseio.com',
    storageBucket: 'app-receita-da11c.appspot.com',
    iosClientId: '636479501272-r0nla6cj545n82qn991tluo8kq3n2u9j.apps.googleusercontent.com',
    iosBundleId: 'com.receitas.app',
  );
}
